version: "3"
services:
  social-network:
    image: social-network:latest
    build:
      context: ../
      dockerfile: build/Dockerfile
    container_name: sn
    ports:
      - "8080:8080"
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-ext
      - sn-net
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    cpus: 2
    mem_limit: 2g
    depends_on:
      - mariadb
      - mariadb-slave
      - redis

  mariadb:
    image: mariadb:10.11.2
    container_name: mariadb
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-net
      - sn-ext
    ports:
      - "3306:3306"
    volumes:
      - social-network-db:/var/lib/mysql
      - ./mariadb-confs/master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mariadb-confs/master/initdb.d:/docker-entrypoint-initdb.d
    cpus: 2
    mem_limit: 2g

  mariadb-slave:
    image: mariadb:10.11.2
    container_name: mariadb-slave
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-net
    volumes:
      - social-network-db-slave:/var/lib/mysql
      - ./mariadb-confs/slave/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mariadb-confs/slave/initdb.d:/docker-entrypoint-initdb.d
    cpus: 2
    mem_limit: 2g
    depends_on:
      - mariadb

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - sn-net
    cpus: 1
    mem_limit: 1g
    depends_on:
    - mariadb

networks:
  sn-ext:
  sn-net:
    internal: true

volumes:
  social-network-db:
  social-network-db-slave:
