version: "3"
services:
  social-network:
    image: social-network:latest
    build:
      context: ../
      dockerfile: build/Dockerfile
    container_name: sn
    ports:
      - "8080:8080"
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-ext
      - sn-net
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    cpus: 2
    mem_limit: 2g
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-net
      - sn-ext
    ports:
      - "5432:5432"
    volumes:
      - sn-pgdb:/var/lib/postgresql/data
    cpus: 2
    mem_limit: 2g

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - sn-net
    cpus: 1
    mem_limit: 1g

networks:
  sn-ext:
  sn-net:
    internal: true

volumes:
  sn-pgdb:
