version: "3"
services:
  social-network:
    image: social-network:latest
    container_name: sn
    ports:
      - "8080:8080"
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-ext
      - sn-net
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    cpus: 4
    mem_limit: 4g


  mariadb:
    image: mariadb:10.11.2
    container_name: mariadb
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-net
    volumes:
      - social-network-db:/var/lib/mysql
      - ./mariadb-confs/master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mariadb-confs/master/initdb.d:/docker-entrypoint-initdb.d
    cpus: 4
    mem_limit: 4g

  mariadb-slave:
    image: mariadb:10.11.2
    container_name: mariadb-slave
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-net
    volumes:
      - social-network-db-slave:/var/lib/mysql
      - ./mariadb-confs/slave/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mariadb-confs/slave/initdb.d:/docker-entrypoint-initdb.d
    cpus: 4
    mem_limit: 4g

networks:
  sn-ext:
  sn-net:
    internal: true

volumes:
  social-network-db:
  social-network-db-slave:
