version: "3"
services:
  social-network:
    image: social-network:latest
    container_name: sn
    ports:
      - "8080:8080"
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-ext
      - sn-net
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 100M


  mariadb:
    image: mariadb:10.5.9
    container_name: mariadb
    env_file: ../.env.docker
    restart: always
    networks:
      - sn-net
    volumes:
      - social-network-db:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 100M

networks:
  sn-ext:
  sn-net:
    internal: true

volumes:
  social-network-db:
